apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::179840394599:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1M9MJB0DHRJJT
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::179840394599:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-20T14:49:20Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1406"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 54f1ca85-1d14-46d9-88e0-dab56e3df879
